#!/usr/bin/env python3

import datetime
import glob
import itertools
import re

import yaml

from markdown_it import MarkdownIt


def find_files():
    for md_file in glob.iglob('*.md'):
        metadata = {'slides': md_file.replace('.md', '.html')}

        with open(md_file) as md_content:
            md = MarkdownIt().parse(md_content.read())
            if md[0].type == 'html_block':
                metadata.update(yaml.safe_load(md[0].content.strip().removeprefix('<!--').removesuffix('-->')))
            for i in [0, 1]:
                if md[i].type == 'heading_open' and 'title' not in metadata:
                    title = md[i+1].content
                    title = re.sub('<[^<]+?>', '', title)
                    metadata['title'] = title

        yield metadata

    for yaml_file in glob.iglob('*.yaml'):
        with open(yaml_file) as f:
            metadata = yaml.safe_load(f)
        yield metadata


HEAD = """
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
</head>
"""
print(HEAD.strip())

all_talks = sorted(find_files(), key=lambda f: f"{f['date']}-{f['title']}", reverse=True)
for year, talks in itertools.groupby(all_talks, key=lambda f: f['date'].year):
    print(f"<h1>{year}</h1>")
    print("<ul>")
    for talk in talks:
        link_text = f"{talk['date']} - {talk['title']}"
        if talk.get('event') is not None:
            link_text += f" ({talk['event']})"
        print("<li>")
        print(f"<a href='{talk['slides']}'>{link_text}</a>")
        if talk.get('video'):
            print(f" (<a href='{talk['video']}'>Video</a>)")
        print("</li>")
    print("</ul>")
