#!/usr/bin/env python3

import datetime
import glob
import re

import yaml

from markdown_it import MarkdownIt


def find_files():
    for md_file in glob.iglob('*.md'):
        metadata = {'filename': md_file, 'html': md_file.replace('.md', '.html') }

        with open(md_file) as md_content:
            md = MarkdownIt().parse(md_content.read())
            if md[0].type == 'html_block':
                metadata.update(yaml.safe_load(md[0].content.strip().removeprefix('<!--').removesuffix('-->')))
            for i in [0, 1]:
                if md[i].type == 'heading_open' and 'title' not in metadata:
                    title = md[i+1].content
                    title = re.sub('<[^<]+?>', '', title)
                    metadata['title'] = title

        if 'date' not in metadata:
            metadata['date'] = datetime.date(1970, 1, 1)

        yield metadata


for f in sorted(find_files(), key=lambda f: f['date'], reverse=True):
    print(f"<a href='{f['html']}'>{f['date']} - {f['title']}</a><br>")
