#!/usr/bin/env python3

import datetime
import glob
import itertools
import re
import sys

import yaml

from markdown_it import MarkdownIt


HTML_HEAD = """
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
</head>
"""


def find_files():
    for md_file in glob.iglob('*.md'):
        metadata = {'slides': md_file.replace('.md', '.html')}

        with open(md_file) as md_content:
            md = MarkdownIt().parse(md_content.read())
            if md[0].type == 'html_block':
                metadata.update(yaml.safe_load(md[0].content.strip().removeprefix('<!--').removesuffix('-->')))
            for i in [0, 1]:
                if md[i].type == 'heading_open' and 'title' not in metadata:
                    title = md[i+1].content
                    title = re.sub('<[^<]+?>', '', title)
                    metadata['title'] = title

        yield metadata

    for yaml_file in glob.iglob('*.yaml'):
        with open(yaml_file) as f:
            metadata = yaml.safe_load(f)
        yield metadata


def build_index(all_talks, output='html'):
    text = ""
    for year, talks in itertools.groupby(all_talks, key=lambda f: f['date'].year):
        text += f"# {year}\n"
        for talk in talks:
            link_text = f"{talk['date']} - {talk['title']}"
            text += f"* [{link_text}]({talk['slides']})"
            if talk.get('link'):
                text += f" ([{talk.get('event', 'Event')}]({talk['link']}))"
            elif talk.get('event'):
                text += f" ({talk['event']})"
            if talk.get('video'):
                text += f" ([Video]({talk['video']}))"
            text += "\n"

    if output == 'html':
        print(HTML_HEAD.strip())
        print(MarkdownIt().render(text))
    else:
        print(text)

if len(sys.argv) == 2:
    output = sys.argv[1]
else:
    output = 'html'

build_index(sorted(find_files(), key=lambda f: f"{f['date']}-{f['title']}", reverse=True), output)
